export const personalInfo = {
  name: 'Hariom Gupta',
  title: 'Flutter & Full-Stack Developer',
  tagline: 'Building AI-powered apps that actually ship',
  email: 'guptahariom049@gmail.com',
  phone: '+91-9315175199',
  location: 'New Delhi, India',
  university: 'GTBIT, GGSIPU (B.Tech IT, 2023-2027)',
  github: 'https://github.com/hariomgupta70427',
  linkedin: 'https://www.linkedin.com/in/hariomgupta70427/',
  twitter: 'https://twitter.com/hariom70427',
  instagram: 'https://www.instagram.com/hariomgupta70427/',
}

export const stats = [
  { label: 'REPOS', value: 26 },
  { label: 'STARS', value: '35+' },
  { label: 'PROJECTS', value: '12+' },
  { label: 'WINNER', value: '10x' },
  { label: 'CGPA', value: '8.2' },
]

export const skills = {
  mobile: {
    name: 'Mobile Dev',
    color: 'skill-mobile',
    items: ['Flutter', 'Dart', 'Java', 'Kotlin', 'Android SDK'],
  },
  ai: {
    name: 'AI & ML',
    color: 'skill-ai',
    items: ['Google Gemini', 'OpenAI', 'Claude', 'Perplexity', 'Hugging Face'],
  },
  frontend: {
    name: 'Frontend',
    color: 'skill-frontend',
    items: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'HTML5/CSS3'],
  },
  backend: {
    name: 'Backend',
    color: 'skill-backend',
    items: ['Node.js', 'Express.js', 'Firebase', 'Supabase', 'MongoDB', 'MySQL'],
  },
  languages: {
    name: 'Languages',
    color: 'skill-languages',
    items: ['Python', 'JavaScript', 'C/C++'],
  },
  devops: {
    name: 'DevOps',
    color: 'skill-devops',
    items: ['Git', 'Docker', 'Vercel', 'Netlify', 'Figma', 'WordPress', 'VS Code', 'GitHub'],
  },
}

export const projects = [
  {
    id: 1,
    name: 'Medical AI Discovery Platform',
    tagline: 'AI-Powered Drug Discovery & Molecular Visualization',
    description: 'Web-based drug discovery platform with molecular visualization, predictive analysis, and integrations with PubChem and IBM RXN APIs for pharmaceutical research.',
    longDescription: 'Built with Next.js and TypeScript, this platform aggregates pharmaceutical research data from multiple APIs. Features molecular structure visualization, AI-powered predictive analysis, and comprehensive drug discovery workflows.',
    tech: ['Next.js', 'TypeScript', 'PubChem API', 'IBM RXN', 'React'],
    color: '#A855F7',
    github: 'https://github.com/hariomgupta70427/medical-ai-platform',
    live: null,
    stars: 8,
    forks: 3,
    highlights: [
      'Molecular structure visualization',
      'AI-powered predictive analysis',
      'PubChem + IBM RXN API integration',
      'Most starred repo — 8 GitHub stars',
    ],
  },
  {
    id: 2,
    name: 'FraudShield',
    tagline: 'AI-Powered Fraud Detection System',
    description: 'Intelligent fraud detection platform that analyzes transaction patterns and flags suspicious activity using machine learning algorithms.',
    longDescription: 'FraudShield uses advanced ML models to detect fraudulent transactions in real-time. Built with a focus on accuracy and speed, it provides detailed risk scoring and explainable AI outputs.',
    tech: ['Python', 'Machine Learning', 'React', 'Node.js', 'Firebase'],
    color: '#FF6B35',
    github: 'https://github.com/hariomgupta70427/FraudShield',
    live: null,
    stars: 0,
    forks: 0,
    highlights: [
      'Real-time fraud detection',
      'ML-powered risk scoring',
      'Explainable AI outputs',
      'Transaction pattern analysis',
    ],
  },
  {
    id: 3,
    name: 'HLedger',
    tagline: 'AI Task Manager & Expense Tracker',
    description: 'Smart chat-based productivity app. Type naturally and AI automatically understands, categorizes, and tracks your expenses and tasks.',
    longDescription: 'Built with Flutter and Google Gemini API, HLedger revolutionizes personal finance tracking. Just type what you spent or what you need to do — the AI handles the rest.',
    tech: ['Flutter', 'Supabase', 'Google Gemini API', 'Dart'],
    color: '#00FF88',
    github: 'https://github.com/hariomgupta70427/HLedger',
    live: null,
    stars: 2,
    forks: 0,
    highlights: [
      'Natural language expense entry',
      'Google Gemini NLP integration',
      'Real-time cross-device sync via Supabase',
      'Combined task + finance management',
    ],
  },
  {
    id: 4,
    name: 'HariWave',
    tagline: 'Modern Audio Streaming Platform',
    description: 'Android app aggregating 100+ free audiobooks and podcasts with a custom player, queue management, and offline support.',
    longDescription: 'HariWave is a full-featured audio streaming app built with Flutter. It aggregates free content from multiple sources, featuring a custom-built audio engine with background playback, playlists, and optimized metadata caching.',
    tech: ['Flutter', 'Android', 'Java', 'Kotlin', 'REST APIs'],
    color: '#FF2D78',
    github: 'https://github.com/hariomgupta70427/HariWave',
    live: null,
    stars: 4,
    forks: 0,
    highlights: [
      '100+ free audiobooks and podcasts',
      'Custom audio player with queue management',
      'Offline support and background playback',
      'Optimized metadata database architecture',
    ],
  },
  {
    id: 5,
    name: 'HaRiverse',
    tagline: 'All-in-One Browser Extension Suite',
    description: '6 productivity tools in one Chrome/Firefox extension — screenshot capture, color picker, QR generator, video speed control, cookie blocker, and theme toggle.',
    longDescription: 'HaRiverse eliminates the need for multiple browser extensions. Built with vanilla JS for maximum performance, it packs 6 essential developer and productivity tools into a single lightweight extension.',
    tech: ['JavaScript', 'CSS', 'Chrome Extension API', 'HTML'],
    color: '#00F5FF',
    github: 'https://github.com/hariomgupta70427/HaRiverse',
    live: null,
    stars: 3,
    forks: 0,
    highlights: [
      '6 tools in one extension',
      'Full-page screenshot capture',
      'Built-in color picker and QR generator',
      'Cookie management and theme toggle',
    ],
  },
]

export const experience = [
  {
    id: 1,
    role: 'IT Systems Manager',
    company: 'TPGCO & GCA',
    duration: 'Jun 2021 - Jan 2023',
    description: 'Led digital transformation initiatives, managed IT infrastructure for a team of 8-10 people, and implemented automation solutions that improved operational efficiency by 25%.',
    highlights: [
      'Managed IT infrastructure for 8-10 team members',
      'Improved system uptime by 25% through proactive maintenance',
      'Administered Windows systems, WordPress platforms, LAN networks',
    ],
  },
  {
    id: 2,
    role: 'Lead Organizer',
    company: 'Math-E-Thon 2.0',
    duration: 'Nov 15-16, 2025',
    description: 'Organized and led a 24-hour international hackathon at GTBIT, GGSIPU with 500+ global teams and a ₹1L+ budget.',
    highlights: [
      '24-hr International Hackathon with 500+ global teams',
      'Managed ₹1L+ event budget',
      'Coordinated logistics, sponsors, judging, participant engagement',
    ],
  },
  {
    id: 3,
    role: 'Freelance Developer',
    company: 'Independent',
    duration: '2024 — Present',
    description: 'Building and delivering custom web and mobile applications for clients. Specializing in Flutter mobile apps, React/Next.js web platforms, and AI-integrated solutions.',
    highlights: [
      'Delivered full-stack web and mobile projects end-to-end',
      'Specialized in Flutter, React, Next.js, and Firebase',
      'AI integration using Google Gemini and OpenAI APIs',
      'Currently available for new freelance projects',
    ],
    tags: ['Flutter', 'React', 'Next.js', 'Firebase', 'AI Integration'],
  },
]

export const achievements = [
  {
    id: 1,
    title: 'Perfect Pitch 2.0',
    subtitle: '🥇 1st Place',
    description: 'Won first place among 20+ teams at Ecell GTBIT pitch competition.',
    date: 'Sept 9, 2025',
    color: '#FFD700',
    org: 'Ecell GTBIT',
  },
  {
    id: 2,
    title: 'Hack with Sanchaar (Circuitrix)',
    subtitle: '🥇 1st Place',
    description: 'First place among 15+ teams at ECE Dept TechFest hackathon.',
    date: 'Sept 10, 2025',
    color: '#FFD700',
    org: 'ECE Dept TechFest',
  },
  {
    id: 3,
    title: 'Srijan 2025',
    subtitle: '🥇 1st Place + Medal + Cash Prize',
    description: 'Won first place, medal, and cash prize at CSE Department event.',
    date: 'Sept 12, 2025',
    color: '#FFD700',
    org: 'CSE Dept, GTBIT',
  },
  {
    id: 4,
    title: 'Oracle Cloud Certified',
    subtitle: '☁️ Certification',
    description: 'Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate.',
    date: '2025',
    color: '#F80000',
    org: 'Oracle Corporation',
  },
  {
    id: 5,
    title: 'Pehchaan Street School',
    subtitle: '📚 Teaching Volunteer',
    description: 'Taught programming fundamentals and digital literacy to underprivileged children as part of a community education initiative.',
    date: '2024',
    color: '#00FF88',
    org: 'NGO Initiative',
  },
  {
    id: 6,
    title: 'Hackathon Organizer',
    subtitle: '🏆 5+ Events Organized',
    description: 'Lead organizer for multiple technical events including Math-E-Thon 1.0 & 2.0, Hack with Ignite, QubitX 2.0, Battle of Codes, and Tech Talk.',
    date: '2024 — 2025',
    color: '#A855F7',
    org: 'GTBIT Technical Committee',
  },
]

export const navLinks = [
  { name: 'About', href: '#about' },
  { name: 'Projects', href: '#projects' },
  { name: 'Experience', href: '#experience' },
  { name: 'Achievements', href: '#achievements' },
  { name: 'Contact', href: '#contact' },
]
